### ISSUE TITLE
Please confirm whether the procedure of preprocssing are done twice in run_mae_pretraining.py ?

### ISSUE THREAD

**Issue by peiliu0408** [MCG-NJU/VideoMAE#10]
Like the tile, I found that the videos are preprocessed twice, refer to:  [dataset](https://github.com/MCG-NJU/VideoMAE/blob/e6c500dd5c8b0df733c54120335d56330def5bd4/datasets.py#L26) and the [train_one_epoch](https://github.com/MCG-NJU/VideoMAE/blob/e6c500dd5c8b0df733c54120335d56330def5bd4/engine_for_pretraining.py#L41). can you help check it ?

**Comment by yztongzhan** [comment]
Hi @peiliu0408! Please refer to the [dataset.py](https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/datasets.py#L41) and [engine_for_pretraining.py](https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/engine_for_pretraining.py#L51-L60) in [MAE-pytorch](https://github.com/pengzhiliang/MAE-pytorch), or the [official implementation](https://github.com/facebookresearch/mae/blob/efb2a8062c206524e35e47d04501ed4f544c0ae8/models_mae.py#L204-L208).
