### ISSUE TITLE
Pre-training and fine-tuning model/scripts on UCF101 or HMDB51

### ISSUE THREAD

**Issue by MsterDC** [MCG-NJU/VideoMAE#11]
Hi,  thanks for sharing your work, it's a brilliant job！

Even though you mentioned training and fine-tuning configurations on **UCF101** and **HMDB51** in the appendix of the paper, I would appreciate if you could provide **pre-trained models** for these two benchmarks, or provide **scripts for training and fine-tuning**. 

Thanks.

**Comment by Morning-YU** [comment]
Hi, MsterDC, can you tell me how to process the UCF101 dataset? What is the format of the data file? Looking forward to your reply！

**Comment by yztongzhan** [comment]
The pre-trained models and scripts on UCF101 are [available](https://github.com/MCG-NJU/VideoMAE/blob/main/MODEL_ZOO.md#UCF101)!
