### ISSUE TITLE
preprocess for ssv2

### ISSUE THREAD

**Issue by liuxingbin** [MCG-NJU/VideoMAE#12]
Could you release the preprocess code for ssv2?
That's will help me a lot.

**Comment by yztongzhan** [comment]
We have provided the pre-processing [script](https://github.com/MCG-NJU/VideoMAE/blob/main/scripts/data/data_clean.py) for SSV2.

**Comment by YHS0201** [comment]
this [script](https://github.com/MCG-NJU/VideoMAE/blob/main/scripts/data/data_clean.py) is not found
