### ISSUE TITLE
Finetune without deepspeed

### ISSUE THREAD

**Issue by OliverRensu** [MCG-NJU/VideoMAE#16]
Fantastic job!  If I try to finetune the model without deepspeed, will the performance drop? Thanks!

**Comment by yztongzhan** [comment]
Hi @OliverRensu! Thanks for your interest in our VideoMAE. 
We did not try to fine-tune the model without deepspeed. Moreover, I conjecture that the performance will not drop, but you may need **more GPU memory** to fine-tune the pre-trained model.
