### ISSUE TITLE
How to extract features using the pre-trained model

### ISSUE THREAD

**Issue by 3DMM-ICME2022** [MCG-NJU/VideoMAE#17]
@yztongzhan @wanglimin  Thanks for your great works!

Could you please tell me how to extract features using the pre-trained model? Could you please provide a script as finetune and pretrain?

Thanks for your nice help!

**Comment by yztongzhan** [comment]
Hi @3DMM-ICME2022! Our VideoMAE is on [🤗HuggingFace Transformers](https://huggingface.co/docs/transformers/main/en/model_doc/videomae) now! You can refer to [the FeatureExtractor](https://huggingface.co/docs/transformers/main/en/model_doc/videomae#transformers.VideoMAEFeatureExtractor) for details about extracting video features.
