### ISSUE TITLE
Why should the video corresponding label be added to the annotations?

### ISSUE THREAD

**Issue by HaleYan** [MCG-NJU/VideoMAE#18]
And can you provide the train.csv file in the form of dataset_root/video_1.mp4 label_1 during the Data Preparation stage

**Comment by yztongzhan** [comment]
Hi @HaleYan!
We didn't use the corresponding label during the pre-training phase.
You can check the code below:
https://github.com/MCG-NJU/VideoMAE/blob/e93f386cffee601cbb01882024255a1dbc23128f/kinetics.py#L471-L493
for details.
