### ISSUE TITLE
tensorRT

### ISSUE THREAD

**Issue by Winnie202** [MCG-NJU/VideoMAE#19]
Thank you very much for your code and contributions. Is it possible to use tensorRT to speed up

**Comment by yztongzhan** [comment]
Hi @Winnie202! Thanks for your interest in our VideoMAE.
We didn't use tensorRT to deploy our ViT backbone on mobile devices. If you want to try this experiment, one tip is that you need to modify the operators using [einops](https://github.com/arogozhnikov/einops) package, which is not supported by tensorRT officially.

**Comment by bit-scientist** [comment]
Hello, @Winnie202 and @yztongzhan, could you give any insights on how to convert the model to tensorRT format?
