### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by ma-siddiqui** [MCG-NJU/VideoMAE#2]
When the code for training and testing will be released?

**Comment by yztongzhan** [comment]
Hi @ma-siddiqui! The code and pre-trained models will be made public in the near future. We also need to follow the company's public process. Thank you all for your patience.

**Comment by gy20073** [comment]
Do you have an ETA?

**Comment by yztongzhan** [comment]
Hi @gy20073! We plan to release the code in one week! Please stay tuned!

**Comment by gy20073** [comment]
> Hi @gy20073! We plan to release the code in one week! Please stay tuned!

Great! Looking forward to it!

**Comment by taokong** [comment]
Also looking forward to the code release

**Comment by yztongzhan** [comment]
Hi @ma-siddiqui @gy20073 @taokong! We have released the code and pre-trained models. Welcome to try out our VideoMAE on video datasets:)
