### ISSUE TITLE
loss_scale_value has no key "scale"

### ISSUE THREAD

**Issue by fanbooo** [MCG-NJU/VideoMAE#21]
Hi author:
    Thanks for your impressive work, I run your code "run_mae_pretraining.py" and it comes an error that "engine_for_pretraining.py", line 79, in train_one_epoch
    loss_scale_value = loss_scaler.state_dict()["scale"]" , as shown below; p.s.  I used the pretrained ssv2's checkpoint;
![342b799fcc675fc5b1e8606ce8073f3dbe3f4e24](https://user-images.githubusercontent.com/27717525/174093401-38b7f072-cb97-401a-9ad0-445631066ab7.png)

**Comment by yztongzhan** [comment]
Hi @fanbooo! Thanks for your interest in our VideoMAE.
We have removed the state_dict["scale"] in the released checkpoints to reduce the size.
Moreover, the pre-trained model are utilize to fine-tune on downstream tasks and you should use 'run_class_finetuning.py' and load the released pre-trained checkpoints.

**Comment by fanbooo** [comment]
Thanks, I am confused, I saw "pre-trained" and "Fine-tune mdoel" in model zoo. If I need to train MAE, which one should I use?













At 2022-06-17 13:29:58, "Zhan Tong" ***@***.***> wrote:

Hi @fanbooo! Thanks for your interest in our VideoMAE.
We have removed the state_dict["scale"] in the released checkpoints to reduce the size.
Moreover, the pre-trained model are utilize to fine-tune on downstream tasks and you should use 'run_class_finetuning.py' and load the released pre-trained checkpoints.

**Comment by zhudongwork** [comment]
> Hi @fanbooo! If you want to train our VideoMAE, please refer to [PRETRAIN.md](https://github.com/MCG-NJU/VideoMAE/blob/main/PRETRAIN.md) and no checkpoint is required.

when I use run_mae_pretraining.py, meet the same probleam
