### ISSUE TITLE
Add the length of the video when preparing datasets

### ISSUE THREAD

**Issue by JiayuZou2020** [MCG-NJU/VideoMAE#24]
According to the code to load data, it seems we should add the length of each video when preparing datasets. See  ` https://github.com/MCG-NJU/VideoMAE/blob/main/DATASET.md` for details. The generated annotation of video datasets should be like:
`dataset_root/video_1.mp4  100 label_1`, where 100 means the length of video_1.mp4.

**Comment by yztongzhan** [comment]
Hi @JiayuZou2020 ! There is no need to add the length of each video. Please check the code below:
https://github.com/MCG-NJU/VideoMAE/blob/e93f386cffee601cbb01882024255a1dbc23128f/kinetics.py#L253

**Comment by klinic** [comment]
According to the code, during the stage of pretrain, I agree to your point that we should add  the length of each video when preparing datasets.
