### ISSUE TITLE
novograd optimizer removed from timm

### ISSUE THREAD

**Issue by DalasNoin** [MCG-NJU/VideoMAE#26]
ModuleNotFoundError: No module named 'timm.optim.novograd'

it seems like timm just gives you nvnovograd if you ask for novograd

https://github.com/rwightman/pytorch-image-models/blob/master/timm/optim/optim_factory.py

    elif opt_lower == 'novograd' or opt_lower == 'nvnovograd':
        optimizer = NvNovoGrad(parameters, **opt_args)

**Comment by yztongzhan** [comment]
Please use `timm==0.4.8/0.4.12`. You can refer to [INSTALL.md](https://github.com/MCG-NJU/VideoMAE/blob/main/INSTALL.md) for more details.

**Comment by Jmh0527** [comment]
I can't find the 0.4.8 version when I install it using pip, and it still prompts the same error after installing 0.4.12, why is that?
