### ISSUE TITLE
MoCoV3 weights

### ISSUE THREAD

**Issue by Separius** [MCG-NJU/VideoMAE#28]
Hi,
First of all, thank you very much for your clean code and impressive results.
Second, is it possible for you to share the weights of the pretrained MoCoV3 baseline?

Best regards,
Sepehr

**Comment by yztongzhan** [comment]
Hi @Separius! Thanks for your interest in our VideoMAE. Unfortunately, we have no plan to release the code and pre-trained models of MoCo v3.

**Comment by fmthoker** [comment]
Hi @yztongzhan,
Can you at least provide some training and finetuning details that you used for UCF101 and Kinetics results?  I am trying to reproduce your baseline number but there are no details in the paper except we follow image-based moco-v3.  Can you please provide more details that could be helpful?
