### ISSUE TITLE
encontered missing keys error while finetunening

### ISSUE THREAD

**Issue by Expert68** [MCG-NJU/VideoMAE#30]
I encontered missing keys error while finetunening, I resume from model pretrained with pretrain model and using it while finetune.
how to solve this problem?
![image](https://user-images.githubusercontent.com/39072886/177960788-74d83c59-12c5-4b75-a0d0-e2f19c6d74d5.png)

**Comment by yztongzhan** [comment]
Hi @Expert68! Please provide your script and more details.

**Comment by Expert68** [comment]
![image](https://user-images.githubusercontent.com/39072886/177963467-a7bbf407-f1ff-4b0d-ad96-b87bf10a914a.png)

**Comment by Expert68** [comment]
I'll check it carefully, please don't close the issue, I will close it while I solve the problem

**Comment by Expert68** [comment]
@yztongzhan problem solved, I did not use script to finetune and default resume parameter is not none which result in this problem

**Comment by Expert68** [comment]
but my pretrained checkpoint is much larger than your's, do you know the reason?
![image](https://user-images.githubusercontent.com/39072886/177967436-6d35f54b-892a-4efc-8ae2-97c4c0d06194.png)
