### ISSUE TITLE
weights from pretrained model "decoder.blocks.0 ... decoder.blocks.1 ..." not used in finetune training?

### ISSUE THREAD

**Issue by fanbooo** [MCG-NJU/VideoMAE#31]
Hi Author:
     I am studying your paper and trained a mae on kinetic dataset, and I have two questions; I would appreciate that if u could give a feedback;
    1. Now I run "run_class_finetuning.py" based on a pretrained model, and warning shows below, is this correct ?
    2. finetuning shows that the GPU occupation is 18G while batchsize are 2, could I freeze the part of foward_feature and only train the 
    classification head?
     
![1a4be17a16632b7fabc25e392844fcf9987ced3a](https://user-images.githubusercontent.com/27717525/178423107-6b852645-971a-4884-9586-aa348531f048.png)

**Comment by yztongzhan** [comment]
Hi @fanbooo! Please make sure you set a **new** `OUTPUT_DIR` during the fine-tuning phase.
