### ISSUE TITLE
Request of a best pretrained checkpoint for downstream tasks

### ISSUE THREAD

**Issue by makecent** [MCG-NJU/VideoMAE#32]
Thanks for you excellent work. With only self-supervised learning, the VideoMAE can perform surprisely well. Besides that, I think the (self-supervised + full-supervised) models are also very meaningful, especially for the downstream tasks/datasets.

@yztongzhan Could you please providing a model/checkpoint that is the best pretrained model you can offer for learning video representation towards any unknown downstream video datasets? 

For example, a model pretrained on the Kinetic-700 with VideoMAE self-supervisly, and then pretrained on Kinetic-700 supervisely.

Such a model should be very useful. One can easily fine-tune it on any downstream datasets for many possible purposes. Just like the ResNet-50 pretrained on ImageNet.

**Comment by Lycus99** [comment]
Theoretically, the feature learned by VideoMAE is powerful for video understanding. I wonder to know that is VideoMAE pretrained model useful for other downstream tasks such as action segmentation? the authors do not give the results on Breakfast or Salad50 or GTEA

**Comment by makecent** [comment]
@Lycus99 For example the AVA dataset for spatial-temporal action deteciton.
![Screenshot from 2022-07-14 16-54-58](https://user-images.githubusercontent.com/42603768/178943969-0ec9c7c9-3f99-496f-8b4a-f412660ac16e.png)

Comparing the last two rows, pretraining on K700 with further supervised training can get better performance
