### ISSUE TITLE
from petrel_client.client import Client

### ISSUE THREAD

**Issue by greggg123** [MCG-NJU/VideoMAE#33]
Hi,

I am trying to use data_clean.py for Kinetics 400 but am unable to use petrel_client from the import statement: 
`from petrel_client.client import Client`
I have installed petrel but that has not worked and I have not been able to find a petrel_client package online.

**Comment by aries-young** [comment]
> Hi,
> 
> I am trying to use data_clean.py for Kinetics 400 but am unable to use petrel_client from the import statement: `from petrel_client.client import Client` I have installed petrel but that has not worked and I have not been able to find a petrel_client package online.

Hello, have you solved this problem? Could you kindly share your solution ?

**Comment by potatowarriors** [comment]
I am also having the same problem. Can you give a little more detailed guide?

**Comment by congee524** [comment]
Sorry, Please remove `from petrel_client.client import Client`, which is used to read data on CephBackend.

**Comment by congee524** [comment]
This is the script file we put up by mistake for processing videos, it has nothing to do with VideoMAE and we will delete the file later.
