### ISSUE TITLE
Mixup and Cutmix

### ISSUE THREAD

**Issue by samrudhdhirangrej** [MCG-NJU/VideoMAE#34]
Hello,

Thank you for sharing your work. I am looking at the code for finetuning the model and trying to understand how to apply mixup and cutmix to videos. The train dataloader seems to provide a batch of size (B, C, T, H, W). However, [the mixup function from timm](https://github.com/rwightman/pytorch-image-models/blob/324a4e58b6b0365d16dcf8f93739be8f74cd7d37/timm/data/mixup.py#L203) requires a batch of size (B, C, H, W). I couldn't find the code for reshaping the batch before sending it to mixup function. Am I missing something? Should we reshape the batch from (B, C, T, H, W) to (B, C\*T, H, W) or (B\*T, C, H, W)? Which is the correct way? 

Thank you.

**Comment by yztongzhan** [comment]
Hi @samrudhdhirangrej! Thanks for your suggestion. We have fixed this bug. Please refer to [mixup.py](https://github.com/MCG-NJU/VideoMAE/blob/5291aaf344ac1856d5bfee7232cf45a7097bd51d/mixup.py#L170) for details.
