### ISSUE TITLE
Preprocessing for UCF101

### ISSUE THREAD

**Issue by greggg123** [MCG-NJU/VideoMAE#35]
Hi, I was wondering if there are any available resources on the preprocessing for UCF101 similar to the given data_clean.py script for SSV2?

**Comment by yztongzhan** [comment]
Hi @greggg123! There is no need to preprocess the videos of UCF101. We use `decord` to decode the raw videos on the fly.

**Comment by yossibiton** [comment]
@yztongzhan 
Where can I get the train.csv, test.csv for UCF101 ?
Can you please provide the csv files you used (as you did for Kinetics) ?

I downloaded the original dataset and it only has these txt files :
classInd.txt
testlist01.txt
testlist02.txt
testlist03.txt
trainlist01.txt
trainlist02.txt
trainlist03.txt

**Comment by wjj-w** [comment]
Hi, have you solved this problem now and what should be done with the UCF101 dataset?

**Comment by yossibiton** [comment]
I believe this dataset has 3 train/test splits.
I don't know which split was used by this repo owners.

**Comment by wjj-w** [comment]
> 

Thank you very much for your reply. I'm trying to randomly select one of the split, but I'm having some problems in generating the csv file ， the video is not being read correctly. Have you successfully generate the csv file based on one of the splitting methods? Can you share it? Looking forward to your reply!
