### ISSUE TITLE
reproduce performance on K400 without using deepspeed

### ISSUE THREAD

**Issue by Christinepan881** [MCG-NJU/VideoMAE#37]
Hi,
Thanks for your work!
When I reproduce the finetuning experiments on K400 without deepspeed backend (by applying your released pretrained checkpoint), I only got 78.0 with VIT-B, which is 2.7% lower than the number (80.7) stated in the paper. Do you know the reason for that? Does the different backend is the main reason?
Thanks!

**Comment by yztongzhan** [comment]
Hi @Christinepan881! Thanks for your interest in our VideoMAE. If you want to fine-tune the pre-trained models, please follow our script and make sure the $total\ batch\ size > 256$.
