### ISSUE TITLE
About preparing SthV2

### ISSUE THREAD

**Issue by klinic** [MCG-NJU/VideoMAE#39]
Hi, Thank you for your work!

I read your 'DATASET.md'. 

Are there  two key points in processing sthv2 datasets: the first is to change the suffix to MP4, the second is to reduce the short side to 320p? (and can only videos with an original height of 240p be zoomed out?)
中文：处理sthv2数据集是不是就2个核心要义：第一个是将后缀改为.mp4，第二个是将短边放缩至320p？（而且是不是只有原始高度为240p的视频才能被选中，然后再去放缩？）

**Comment by congee524** [comment]
resizing the video just to reduce the IO overhead.
