### ISSUE TITLE
Missing Comparison with MaskFeat

### ISSUE THREAD

**Issue by vaesl** [MCG-NJU/VideoMAE#4]
Good job! After reading your VideoMAE, I feel this work should compare with MaskFeat [https://arxiv.org/abs/2112.09133] regarding to both method and performance. MaskFeat, the concurrent work with MAE (ImageMAE), also performs the masked image modelling for video classification task. The main difference between the MaskFeat and VideoMAE is that the reconstructed target is different (HOG feature vs. RGB image). Interest not relevant. It is just my personal opinion.

**Comment by yztongzhan** [comment]
Hi @vaesl! Thanks for your advice. We will consider it.
