### ISSUE TITLE
How is the Classifcation Head added onto the encoder?

### ISSUE THREAD

**Issue by PascalHbr** [MCG-NJU/VideoMAE#42]
Looking in into the code, I can find a linear layer on top of the pre-trained encoder that looks as follows (for kinetics400):

```
      (11): Block(
        (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (attn): Attention(
          (qkv): Linear(in_features=768, out_features=2304, bias=False)
          (attn_drop): Dropout(p=0.0, inplace=False)
          (proj): Linear(in_features=768, out_features=768, bias=True)
          (proj_drop): Dropout(p=0.0, inplace=False)
        )
        (drop_path): DropPath(p=0.10000000149011612)
        (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): Mlp(
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (act): GELU()
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (drop): Dropout(p=0.0, inplace=False)
        )
      )
    )
    (norm): Identity()
    (fc_norm): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
    (head): Linear(in_features=768, out_features=400, bias=True)
```
What I don't understand is, how exactly the layer is connected to the encoder. The encoder should deliver N (sequence length) tokens with d dimensions (768 in this case). Did you employ a CLS token (I don't think so), are you taking the mean over the N tokens or how exactly do you connect the encoder to the classification head? I cannot find any information on that in your paper, I might be wrong though - sorry in this case :)

**Comment by yztongzhan** [comment]
Please refer to [FINETUNE.md](https://github.com/MCG-NJU/VideoMAE/blob/main/FINETUNE.md#note) for details.
