### ISSUE TITLE
Hi ,Could you provide AVA Pretrained model?

### ISSUE THREAD

**Issue by GuardSkill** [MCG-NJU/VideoMAE#44]
Thank you very much

**Comment by zhixuany** [comment]
Great work! I also would like to have access to an AVA pretrained model if possible. Thanks!

**Comment by TomRaz** [comment]
+1

**Comment by yztongzhan** [comment]
Hi @GuardSkill @zhixuany @TomRaz @yan-ctrl ! We have released the code and checkpoints for AVA. Please check [VideoMAE-Action-Detection](https://github.com/MCG-NJU/VideoMAE-Action-Detection) for more details.
