### ISSUE TITLE
Pretraining time for UCF101

### ISSUE THREAD

**Issue by itsmag11** [MCG-NJU/VideoMAE#48]
Hello author,

I saw you mentioned there were 8 GPUs used for pretraining 9.5k UCF101 video clips. May I ask what the total pretraining time for pretraining UCF101 for 3200 epochs using batch size 192 (the setting in your paper) is?

Appreciate it!

**Comment by yztongzhan** [comment]
Hi @itsmag11! It takes about 30 hours to  pre-train VideoMAE on UCF101 for 3200 epochs.
Besides, the pre-trained models and scripts on UCF101 are [available](https://github.com/MCG-NJU/VideoMAE/blob/main/MODEL_ZOO.md#UCF101)!
