### ISSUE TITLE
Training receipt for AVA

### ISSUE THREAD

**Issue by tztztztztz** [MCG-NJU/VideoMAE#49]
Thanks for the excellent work! 

Could you provide the training configuration for the AVA dataset? I tried to reproduce the results but observed overfitting.

**Comment by duytue-kite** [comment]
Hi @tztztztztz,
Have you been able to train this with AVA dataset?
I'm also interested in getting this model to work with AVA but I don't know where to start.
Can you show me how to add ava head and train it?
Thanks!

**Comment by TomRaz** [comment]
+1

**Comment by yan-ctrl** [comment]
+1

**Comment by yztongzhan** [comment]
Hi @tztztztztz @duytue-kite @TomRaz @yan-ctrl ! We have released the code and checkpoints for AVA. Please check [VideoMAE-Action-Detection](https://github.com/MCG-NJU/VideoMAE-Action-Detection) for more details.
