### ISSUE TITLE
Pretraining time

### ISSUE THREAD

**Issue by jzhang38** [MCG-NJU/VideoMAE#5]
Hi, thanks for your solid works!

Would you mind sharing some pretraining time statistics? Like how long does it take to pretrain on Kinetics400 using 64 V100s.

**Comment by yztongzhan** [comment]
Hi @jzhang38! Thanks for your question! It takes about **27 hours** to pre-train our VideoMAE (ViT-B) for 800 epochs on Kinetics-400 using 64 Tesla V100 GPUs. If you find the `GPU-Util` is not high enough, please reduce the batch-size to alleviate the pressure of your CPUs and I/O.
