### ISSUE TITLE
pretrained models on ImageNet1K

### ISSUE THREAD

**Issue by zhaiqx** [MCG-NJU/VideoMAE#50]
Hi,

Thank you for sharing the exciting work!

Could you please release the pre-trained models on ImageNet1K(with input_size 224x224 or 320x320)?

Many many thanks!

**Comment by yztongzhan** [comment]
Hi @zhaiqx! Please refer to [MAE-pytorch](https://github.com/pengzhiliang/MAE-pytorch) or [mae](https://github.com/facebookresearch/mae) for the pre-trained models on ImageNet1K.
