### ISSUE TITLE
ImportError: cannot import name 'VideoMAEFeatureExtractor' from 'transformers'

### ISSUE THREAD

**Issue by likhith00** [MCG-NJU/VideoMAE#51]
Hi! 

tried to replicate the steps present in hugging face in google colab and got this
**ImportError: cannot import name 'VideoMAEFeatureExtractor' from 'transformers'.**

if this is a version issue, can you specify the version of transformers to be used ? 

thanks.

**Comment by yztongzhan** [comment]
Hi @likhith00! I try the inference [ipynb](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/VideoMAE/Quick_inference_with_VideoMAE.ipynb) just now and it works well! Could you try it again?

**Comment by likhith00** [comment]
Hi @yztongzhan! this link works for me. Thanks for the help.

> Hi @likhith00! I try the [inference ipynb](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/VideoMAE/Quick_inference_with_VideoMAE.ipynb) (or [this colab link](https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/VideoMAE/Quick_inference_with_VideoMAE.ipynb)) just now and it works well! Could you try it again?
