### ISSUE TITLE
mask_type random

### ISSUE THREAD

**Issue by WEIZHIHONG720** [MCG-NJU/VideoMAE#52]
Hi, could you please provide the code version for mask_type=random? Thank you very much for your work.

**Comment by dfan** [comment]
I think you can just copy the tube masking class and replace _call__ with something like this. Then in `dataset.py`, add an additional condition in DataAugmentationForVideoMAE class constructor.

```
mask = []
for i in range(self.frames):
    mask_per_frame = np.hstack([
        np.zeros(self.num_patches_per_frame - self.num_masks_per_frame),
        np.ones(self.num_masks_per_frame),
    ])
    np.random.shuffle(mask_per_frame)
    mask.append(mask_per_frame)

mask = np.array(mask)
mask = mask.flatten()
return mask 
```

**Comment by hxi667** [comment]
> Hi, could you please provide the code version for mask_type=random? Thank you very much for your work.

I have the same problem, did you find a solution?
