### ISSUE TITLE
The log file of pretrain and finetune stage

### ISSUE THREAD

**Issue by sakura2233565548** [MCG-NJU/VideoMAE#53]
Thanks for your contribution to this community! Could you provide the log file of pre-train stage and fine-tune stage for better reproduction? I'd appreciate it if you can provide the files.

**Comment by yztongzhan** [comment]
Hi @sakura2233565548! Please check [MODEL_ZOO.md](https://github.com/MCG-NJU/VideoMAE/blob/main/MODEL_ZOO.md).

**Comment by sakura2233565548** [comment]
Thanks a lot! I missed this important part.
