### ISSUE TITLE
patch embedding way in the random masking scheme

### ISSUE THREAD

**Issue by misoyuri** [MCG-NJU/VideoMAE#61]
Hi Zhan,

Thank you for your excellent work!

We are trying to use your code to reproduce your experiment in Table1-(b).
However, we are now having some trouble with patch embedding manner when we use random mask sampling.

In your current code implementations of pretraining, the patch embedding works with each 2-frames.
But, if we would do the same manner, the masking information in the same position of different frames will be not the same because of random masking sampling.

so, I want to ask you how to handle the patch embedding when you did experiments about random masking sampling.

Thank you.

**Comment by yztongzhan** [comment]
You can implement random masking scheme as follow:
```
class RandomMaskingGenerator:
    def __init__(self, input_size, mask_ratio):
        if not isinstance(input_size, tuple):
            input_size = (input_size,) * 3

        self.frames, self.height, self.width = input_size

        self.num_patches = self.frames *  self.height * self.width # 8x14x14
        self.num_mask = int(mask_ratio * self.num_patches)

    def __repr__(self):
        repr_str = "Maks: total patches {}, mask patches {}".format(
            self.num_patches, self.num_mask
        )
        return repr_str

    def __call__(self):
        mask = np.hstack([
            np.zeros(self.num_patches - self.num_mask),
            np.ones(self.num_mask),
        ])
        np.random.shuffle(mask)
        return mask # [196*8]
```
