### ISSUE TITLE
Is position embedding useless?

### ISSUE THREAD

**Issue by kun-dragon** [MCG-NJU/VideoMAE#63]
Thanks for you great job! And I have a question.
There are position embedding in several video transformers, such as, TimeSformer, VIVit. But I didn't find anything about it in paper or code. Is position embedding useless for VideoMAE?

**Comment by yztongzhan** [comment]
Please check the implementation [here](https://github.com/MCG-NJU/VideoMAE/blob/b6af64a997da1a2f52ce1cb2f300712faa2444a1/modeling_finetune.py#L212).

**Comment by kun-dragon** [comment]
Thanks a lot.
