### ISSUE TITLE
Why do not load the best ckpt for final test during downstream finetuning?

### ISSUE THREAD

**Issue by youcaiSUN** [MCG-NJU/VideoMAE#68]
Hi,
It seems that the model in the last epoch will be used for test, why not use the best saved ckpt during validation?
https://github.com/MCG-NJU/VideoMAE/blob/826dfa6d4fa54da21fe470bc0471a4de83f3acd1/run_class_finetuning.py#L542

Thanks!

**Comment by congee524** [comment]
There is little difference between the last ckpt and the best ckpt unless overfit. But you may modify the code to reload the best-ckpt.

**Comment by youcaiSUN** [comment]
Got it, thanks!
