### ISSUE TITLE
how to preprosessing?

### ISSUE THREAD

**Issue by hic9507** [MCG-NJU/VideoMAE#7]
Hello. 
First, thank you for this repository.

I'm trying to preprocess.

I already looked at install.md and installed it.
Now look at data.md and try to follow it.
However, I already have the kinetics-400 downloaded before, so I just need to pre-process the data.

i) Download the dataset from the official website.

ii) Preprocess the dataset by resizing the short edges of the video to 320px. You can refer to the MMAction2 data benchmark for TSN and SlowOnly.

iii) Create the annotations required by the dataloader ("<path_to_video> <video_class>" in the annotations). Comments usually include train.csv, val.csv, and test.csv (here val.csv is equivalent to test.csv). The file format *.csv is:

I'm on the second of this course you mentioned, and I'm not sure how to do it. How do I pre-process?

Thank you for read it!

**Comment by yztongzhan** [comment]
Hi @hic9507! Thanks for your question. You can refer to this [script](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/resize_videos.py) for help.

**Comment by hic9507** [comment]
Can you give me an example of the command?
I'm a newb so I don't know.
First of all, thanks for the reply!

**Comment by yztongzhan** [comment]
You can refer to the [instruction(en)](https://github.com/open-mmlab/mmaction2/blob/ed53d94336bedbb385445d59bba31121951c5c37/tools/data/kinetics/README.md#step-2-prepare-videos) or [中文说明](https://github.com/open-mmlab/mmaction2/blob/ed53d94336bedbb385445d59bba31121951c5c37/tools/data/kinetics/README_zh-CN.md#2-%E5%87%86%E5%A4%87%E8%A7%86%E9%A2%91) for help.
