### ISSUE TITLE
Can't download SSv2 ViT-B pre-trained model

### ISSUE THREAD

**Issue by sunilhoho** [MCG-NJU/VideoMAE#74]
Hi, thanks for your excellent work.

As I mentioned in title, I need permission for downloading the ViT-B pre-trained model on SSv2(https://drive.google.com/file/d/1I18dY_7rSalGL8fPWV82c0-foRUDzJJk/view?usp=sharing). Can I have permission(sunilhoho93@gmail.com)?

**Comment by yztongzhan** [comment]
I have changed the permission of the pre-trained models. Please feel free to use them.
