### ISSUE TITLE
No such file or directory: '/home/zhiyuan/img_diff_sthv1_train.json'

### ISSUE THREAD

**Issue by rouge012** [MCG-NJU/VideoMAE#79]
I got the error when I run VideoMAE model in mmaction2.

![image](https://user-images.githubusercontent.com/104661419/221852473-04876530-5f9b-4504-87bd-59bcbae22b17.png)

**Comment by yztongzhan** [comment]
/home/zhiyuan/img_diff_sthv1_train.json might be a json file in MGSampler.
