### ISSUE TITLE
How many videos are in your validation set?

### ISSUE THREAD

**Issue by Sumutan** [MCG-NJU/VideoMAE#94]
In the original paper of K400, the validation set appears to have 19761 items (at least we found a version with more than 19k items), but the K400 official website currently provides a validation set with only 17747 items. Could you please tell me how many items are in the K400 validation set that you used?

**Comment by yztongzhan** [comment]
Hi @Sumutan ! [OpenDataLab](https://opendatalab.com/) provides a copy of [Kinetics400](https://opendatalab.com/Kinetics-400) dataset, you can download Kinetics dataset with **short edge 320px** from [here](https://opendatalab.com/Kinetics-400). All experiments on Kinetics-400 in VideoMAE are based on [this version](https://opendatalab.com/Kinetics-400).

**Comment by Sumutan** [comment]
Thank you！

**Comment by Sumutan** [comment]
We tried the download link you provided, but we couldn't extract the second file (51G) after downloading it. Have you encountered this situation before? Are there any other download channels available?
![image](https://user-images.githubusercontent.com/49645831/233789438-0fd73a37-1730-47f5-bbf6-f352f6da01d7.png)

**Comment by EvenGu** [comment]
@Sumutan Hey, have you solved this? I'm having the same issue with the second file (0001) ...

**Comment by Sumutan** [comment]
@EvenGu Sorry, it's been a while and I forgot the specific extraction code. It might involve using commands like `cat` to concatenate the files before extracting, such as:

```
cat Kinetics-400.tar.gz.* > Kinetics-400.tar.gz
tar -xzvf Kinetics-400.tar.gz
```


(Note: The above commands are provided by AI and may not run correctly.)
